import React,{useEffect,useMemo,useState} from 'react'; import {createRoot} from 'react-dom/client'; import type {FileNode} from '@orbit/shared'; import './style.css';

type AppId='files'|'notes'|'terminal'|'code'|'settings'; type Win={id:string;app:AppId;title:string;x:number;y:number;w:number;h:number;min?:boolean;max?:boolean;z:number};
const apps:Record<AppId,{icon:string;name:string;desc:string}>={files:{icon:'▰',name:'Files',desc:'Persistent virtual filesystem'},notes:{icon:'✎',name:'Notes',desc:'Local-first document editor'},terminal:{icon:'›_',name:'Terminal',desc:'Sandbox execution console'},code:{icon:'⌘',name:'Workspace',desc:'Code and project editor'},settings:{icon:'⚙',name:'Settings',desc:'Environment preferences'}};
class Vfs { db!:IDBDatabase; async open(){this.db=await new Promise((r,j)=>{const q=indexedDB.open('orbit-fs',1);q.onupgradeneeded=()=>q.result.createObjectStore('nodes',{keyPath:'path'});q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});if(!(await this.list()).length){await this.put({path:'/Welcome.md',name:'Welcome.md',parent:'/',kind:'file',updatedAt:Date.now(),size:151,mime:'text/markdown'});await this.put({path:'/Projects',name:'Projects',parent:'/',kind:'directory',updatedAt:Date.now(),size:0});await this.put({path:'/Projects/hello.js',name:'hello.js',parent:'/Projects',kind:'file',updatedAt:Date.now(),size:45,mime:'text/javascript'});}} tx(mode:IDBTransactionMode){return this.db.transaction('nodes',mode).objectStore('nodes')} async list(){return await new Promise<FileNode[]>(r=>{const q=this.tx('readonly').getAll();q.onsuccess=()=>r(q.result)})} async put(x:FileNode){await new Promise<void>((r,j)=>{const q=this.tx('readwrite').put(x);q.onsuccess=()=>r();q.onerror=()=>j(q.error)})} async remove(path:string){await new Promise<void>(r=>{const q=this.tx('readwrite').delete(path);q.onsuccess=()=>r()})}}
const fs=new Vfs();
function App(){const [wins,setWins]=useState<Win[]>([]),[launch,setLaunch]=useState(false),[query,setQuery]=useState(''),[online,setOnline]=useState(navigator.onLine),[toast,setToast]=useState(''),[active,setActive]=useState('Main'); const [z,setZ]=useState(5);
useEffect(()=>{fs.open();const on=()=>{setOnline(navigator.onLine);setToast(navigator.onLine?'Connection restored — sync queue processing':'Offline — changes remain on this device')};addEventListener('online',on);addEventListener('offline',on);const k=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setLaunch(true)};if(e.key==='Escape')setLaunch(false)};addEventListener('keydown',k);return()=>{removeEventListener('online',on);removeEventListener('offline',on);removeEventListener('keydown',k)}} ,[]);
const open=(app:AppId)=>{const a=apps[app];setZ(v=>v+1);setWins(w=>[...w,{id:crypto.randomUUID(),app,title:a.name,x:90+w.length*24,y:70+w.length*20,w:app==='code'?760:620,h:440,z:z+1}]);setLaunch(false)};const focus=(id:string)=>setWins(w=>w.map(x=>x.id===id?{...x,z:z+1}:x)); const filtered=Object.entries(apps).filter(([,a])=>a.name.toLowerCase().includes(query.toLowerCase()));
return <main className="desktop"><div className="orb one"/><div className="orb two"/><header><button className="brand" onClick={()=>setLaunch(true)}>◈ orbit</button><span className="crumb">{active} workspace</span><div className="status"><span className={online?'online':'offline'}>● {online?'Synced':'Offline'}</span><button onClick={()=>setToast('No new notifications')}>◌</button><time>{new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div></header><section className="desktop-icons">{Object.entries(apps).slice(0,3).map(([id,a])=><button key={id} onDoubleClick={()=>open(id as AppId)}><b>{a.icon}</b><span>{a.name}</span></button>)}</section>
{wins.map(w=><Window key={w.id} w={w} onClose={()=>setWins(s=>s.filter(x=>x.id!==w.id))} onMin={()=>setWins(s=>s.map(x=>x.id===w.id?{...x,min:true}:x))} onFocus={()=>focus(w.id)}>{w.app==='files'?<Files notify={setToast}/>:w.app==='notes'?<Notes notify={setToast}/>:w.app==='terminal'?<Terminal/>:w.app==='code'?<Code/>:<Settings/>}</Window>)}
{launch&&<div className="overlay" onMouseDown={()=>setLaunch(false)}><section className="launcher" onMouseDown={e=>e.stopPropagation()}><input autoFocus aria-label="Search applications, files, and settings" value={query} onChange={e=>setQuery(e.target.value)}/><small>SEARCH APPLICATIONS, FILES, SETTINGS · CTRL K</small>{filtered.map(([id,a])=><button key={id} onClick={()=>open(id as AppId)}><b>{a.icon}</b><span>{a.name}<i>{a.desc}</i></span><kbd>↵</kbd></button>)}</section></div>}
<nav className="dock"><button onClick={()=>setLaunch(true)}>◈</button>{Object.entries(apps).map(([id,a])=><button key={id} aria-label={a.name} onClick={()=>{const m=wins.find(x=>x.app===id);m?setWins(s=>s.map(x=>x.id===m.id?{...x,min:false,z:z+1}:x)):open(id as AppId)}}>{a.icon}<em>{wins.some(x=>x.app===id)?'•':''}</em></button>)}<span/><button onClick={()=>setActive(active==='Main'?'Focus':'Main')}>{active==='Main'?'▣':'▤'}</button></nav>{toast&&<div className="toast" onAnimationEnd={()=>setToast('')}>{toast}</div>}</main>}
function Window(p:{w:Win;children:React.ReactNode;onClose:()=>void;onMin:()=>void;onFocus:()=>void}){const {w}=p;const [pos,setPos]=useState({x:w.x,y:w.y});const drag=(e:React.PointerEvent)=>{const sx=e.clientX-pos.x,sy=e.clientY-pos.y;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);const move=(q:PointerEvent)=>setPos({x:Math.max(0,q.clientX-sx),y:Math.max(35,q.clientY-sy)});addEventListener('pointermove',move,{once:false});addEventListener('pointerup',()=>removeEventListener('pointermove',move),{once:true})};if(w.min)return null;return <article className={'window '+(w.max?'max':'')} style={{left:pos.x,top:pos.y,width:w.w,height:w.h,zIndex:w.z}} onMouseDown={p.onFocus}><div className="titlebar" onPointerDown={drag}><span className="traffic"><i/><i/><i/></span><strong>{w.title}</strong><div><button onClick={p.onMin}>—</button><button onClick={p.onClose}>×</button></div></div><div className="appbody">{p.children}</div></article>}
function Files({notify}:{notify:(x:string)=>void}){const [nodes,setNodes]=useState<FileNode[]>([]),[selected,setSelected]=useState('');const load=()=>fs.list().then(setNodes);useEffect(()=>{load()},[]);const create=async()=>{const n=prompt('Name your file','Untitled.md');if(n){await fs.put({path:'/'+n,name:n,parent:'/',kind:'file',size:0,updatedAt:Date.now(),mime:'text/plain'});load();notify('File created and queued for sync')}};return <div className="files"><aside><b>ORBIT DRIVE</b><button>⌂ Home</button><button>▱ Recent</button><button>☆ Starred</button><hr/><small>LOCATIONS</small><button>◫ Projects</button></aside><section><div className="toolbar"><strong>Home</strong><span/><button onClick={create}>+ New file</button><button onClick={load}>↻</button></div><div className="filegrid">{nodes.map(n=><button className={selected===n.path?'selected':''} onClick={()=>setSelected(n.path)} key={n.path}><b>{n.kind==='directory'?'▣':'▤'}</b><span>{n.name}<small>{n.kind} · {new Date(n.updatedAt).toLocaleDateString()}</small></span></button>)}</div></section></div>}
function Notes({notify}:{notify:(s:string)=>void}){const [text,setText]=useState('# Morning brief\n\nYour local-first notes stay available without a connection.');const [saved,setSaved]=useState('Saved locally');useEffect(()=>{const t=setTimeout(()=>{localStorage.setItem('orbit-note',text);setSaved('Saved locally · sync queued')},450);return()=>clearTimeout(t)},[text]);useEffect(()=>{setText(localStorage.getItem('orbit-note')||text)},[]);return <div className="notes"><aside><button>+ New note</button><b>Morning brief</b><span>Welcome to Orbit</span><span>Project outline</span></aside><section><div className="editorbar"><strong>Morning brief</strong><small>{saved}</small></div><textarea aria-label="Note editor" value={text} onChange={e=>{setText(e.target.value);setSaved('Saving…')}} onBlur={()=>notify('Note saved locally')}/></section></div>}
function Terminal(){const [lines,setLines]=useState(['orbit sandbox v1 · capability-limited session','Type “help” for supported commands.']);const [cmd,setCmd]=useState('');const run=(e:React.FormEvent)=>{e.preventDefault();const out=cmd==='help'?'help  clear  date  echo <text>  ls':cmd==='date'?new Date().toString():cmd==='clear'?'':cmd.startsWith('echo ')?cmd.slice(5):cmd==='ls'?'Welcome.md  Projects/':`orbit: ${cmd}: command unavailable in browser sandbox`;setLines(cmd==='clear'?[]:x=>[...x,'› '+cmd,out]);setCmd('')};return <div className="terminal">{lines.map((x,i)=><div key={i}>{x}</div>)}<form onSubmit={run}><span>›</span><input autoFocus value={cmd} onChange={e=>setCmd(e.target.value)} aria-label="Terminal command"/></form></div>}
function Code(){const [code,setCode]=useState("export function greet(name) {\n  return `Hello, ${name}.`;\n}\n\nconsole.log(greet('Orbit')); ");return <div className="code"><aside><b>EXPLORER</b><span>⌄ PROJECTS</span><button>▤ hello.js</button><button>▤ README.md</button></aside><section><div className="tabs"><b>JS&nbsp; hello.js</b><span>×</span></div><textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck="false"/></section></div>}
function Settings(){return <div className="settings"><aside><b>SETTINGS</b>{['Appearance','Desktop behavior','Notifications','Workspaces','Keyboard shortcuts','Storage & sync','Account'].map(x=><button key={x}>{x}</button>)}</aside><section><h2>Appearance</h2><p>Make Orbit feel like your environment.</p><label>Theme<select defaultValue="Midnight"><option>Midnight</option><option>System</option><option>Light</option></select></label><label>Reduced motion <input type="checkbox"/></label><hr/><h3>Synchronization</h3><p><span className="online">●</span> Local store healthy · Remote provider not configured</p></section></div>}
createRoot(document.getElementById('root')!).render(<App/>);
